@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version  = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"
String imageTag = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/promu:' + imageTag ): 'olcne/promu:' + imageTag],
        platforms: [ 'ol8', 'ol9'],
        architectures: ['x86_64', 'aarch64'],
        buildScript: "sh olm/build-image.sh"
)
